storage_adapters:
  dlx.testing.article:
    class: Daikon\CouchDb\Storage\CouchDbStorageAdapter
    connector: dlx.testing.event_store
    settings:
      design_doc: dlx-testing-article

stream_stores:
  dlx.testing.article:
    class: Daikon\CouchDb\Storage\CouchDbStreamStorage
    storage_adapter: dlx.testing.article

units_of_work:
  dlx.testing.article:
    class: Dailex\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    stream_store: dlx.testing.article
    aggregate_root: Dlx\Testing\Article\Domain\Article